name: Deploy NodeJs app on checkout
on: [push]
jobs:
  push-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build image on checkout
        uses: actions/checkout@v3
        run: docker build -t ghcr.io/romansabechkine/node-app .

      - name: Log to github container registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: $ {{github.actor}}
         password: $ {{secrets.GITHUB_TOKEN}}

      - name: push the image to github container registry
        run: docker push ghcr.io/romansabechkine/node-app:latest
      